package net.thunderbird.core.common.evaarta

data class EvaartaWorkTask(val id:String,val title:String,val status:String="inbox",val priority:String="medium",val assigneeId:String?=null,val teamId:String?=null,val projectId:String?=null,val parentId:String?=null,val dependsOn:List<String>=emptyList(),val estimateMinutes:Int=0,val remainingMinutes:Int=estimateMinutes,val progress:Int=0,val skills:List<String>=emptyList(),val evidenceIds:List<String>=emptyList(),val decisionIds:List<String>=emptyList(),val sourceIds:List<String>=emptyList(),val dueEpochMs:Long?=null,val updatedEpochMs:Long=System.currentTimeMillis(),val assignmentState:String="none")
data class EvaartaCandidate(val id:String,val skills:Set<String>=emptySet(),val capacityMinutes:Int=0,val committedMinutes:Int=0,val authorized:Boolean=true,val projectIds:Set<String>=emptySet())
data class EvaartaWorkload(val personId:String,val capacityMinutes:Int,val committedMinutes:Int,val availableMinutes:Int,val utilization:Double,val overloaded:Boolean)
data class EvaartaWorkHealth(val health:String,val score:Int,val overdue:Boolean,val stalled:Boolean,val missingEvidence:Boolean,val causes:Set<String>)
data class EvaartaRisk(val id:String,val title:String,val probability:Double,val impact:Double,val ownerId:String?=null,val evidenceIds:List<String>=emptyList(),val status:String="open")
object EvaartaTaskWorkOperatingSystem{
 val states=setOf("inbox","planned","ready","offered","assigned","accepted","in-progress","waiting","blocked","review","approved","verified","done","cancelled","deferred","rejected","duplicate")
 fun assign(t:EvaartaWorkTask,c:EvaartaCandidate)=t.copy(assigneeId=c.id,assignmentState="offered",status="offered")
 fun negotiate(t:EvaartaWorkTask,state:String)=t.copy(assignmentState=state,status=if(state=="accepted")"accepted" else if(state=="declined")"rejected" else "offered")
 fun validateGraph(ts:List<EvaartaWorkTask>):Boolean{val seen=mutableSetOf<String>();val visiting=mutableSetOf<String>();fun d(id:String):Boolean{if(id in visiting)return false;if(id in seen)return true;val t=ts.firstOrNull{it.id==id}?:return false;visiting+=id;if(t.dependsOn.any{!d(it)})return false;visiting-=id;seen+=id;return true};return ts.all{d(it.id)}}
 fun workload(ts:List<EvaartaWorkTask>,capacity:Map<String,Int>)=capacity.map{(id,cap)->val c=ts.filter{it.assigneeId==id&&!setOf("done","verified","cancelled").contains(it.status)}.sumOf{it.remainingMinutes};EvaartaWorkload(id,cap,c,maxOf(0,cap-c),if(cap>0)c.toDouble()/cap else 0.0,c>cap)}
 fun score(t:EvaartaWorkTask,c:EvaartaCandidate):Double{val skill=if(t.skills.isEmpty())1.0 else t.skills.count{it in c.skills}.toDouble()/t.skills.size;val availability=if(c.capacityMinutes>0)maxOf(0.0,(c.capacityMinutes-c.committedMinutes).toDouble()/c.capacityMinutes)else 1.0;val membership=if(t.projectId==null||t.projectId in c.projectIds)1.0 else 0.0;return .45*skill+.35*availability+.20*membership}
 fun recommend(t:EvaartaWorkTask,cs:List<EvaartaCandidate>)=cs.filter{it.authorized}.map{it.id to score(t,it)}.sortedByDescending{it.second}
 fun monitor(t:EvaartaWorkTask,now:Long=System.currentTimeMillis(),staleHours:Long=72):EvaartaWorkHealth{val overdue=t.dueEpochMs?.let{now>it&&!setOf("done","verified","cancelled").contains(t.status)}?:false;val stalled=now-t.updatedEpochMs>=staleHours*3600000;val unassigned=t.assigneeId==null&&t.teamId==null;val h=when{t.status=="blocked"->"blocked";unassigned->"unassigned";t.assignmentState=="offered"->"unaccepted";overdue->"late";stalled->"stalled";else->"on-track"};var s=100;if(overdue)s-=30;if(stalled)s-=20;if(h=="blocked")s-=25;if(unassigned)s-=15;return EvaartaWorkHealth(h,s,overdue,stalled,t.status=="review"&&t.evidenceIds.isEmpty(),if(h=="blocked")setOf("dependency")else emptySet())}
 fun impact(ts:List<EvaartaWorkTask>,id:String):Set<String>{val out=mutableSetOf<String>();var q=listOf(id);while(q.isNotEmpty()){val next=ts.filter{it.dependsOn.any{d->q.contains(d)}&&!out.contains(it.id)}.map{it.id};out+=next;q=next};return out}
 fun verify(t:EvaartaWorkTask,allowWithoutEvidence:Boolean=false):EvaartaWorkTask{require(allowWithoutEvidence||t.evidenceIds.isNotEmpty());return t.copy(status="verified")}
 fun decisionToTask(id:String,title:String,evidence:List<String>,sources:List<String>)=EvaartaWorkTask(id,title,status="planned",decisionIds=listOf(id),evidenceIds=evidence,sourceIds=sources)
 fun evidenceToTask(id:String,title:String,evidenceId:String,sourceId:String?=null)=EvaartaWorkTask(id,title,status="planned",evidenceIds=listOf(evidenceId),sourceIds=listOfNotNull(sourceId))
 fun projectHealth(ts:List<EvaartaWorkTask>)=if(ts.any{monitor(it).health in setOf("blocked","late")})"at-risk" else if(ts.any{monitor(it).health in setOf("stalled","unassigned","unaccepted")})"watch" else "on-track"
}
